on: [push, pull_request]
name: Flatpak
jobs:
  flatpak-builder:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nahuelwexd/flatpak-builder-action@freedesktop-19-08
      with:
        manifest-path: org.example.MyApp.yml
        meson-args: -Dprofile=development
        flatpak-module: testproject
        app-id: org.example.MyApp.Devel
        bundle: org.example.MyApp.Devel.flatpak
